# SOURCE: https://cloud.google.com/kubernetes-engine/docs/tutorials/guestbook
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-follower
  namespace: submariner-demo
  labels:
    app: redis-follower
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-follower
  template:
    metadata:
      labels:
        app: redis-follower
    spec:
      containers:
      - name: follower
        image: gcr.io/google_samples/gb-redis-follower:v2
        env:
        - name: REDIS_LEADER_SERVICE_HOST
          value: redis-leader.submariner-demo.svc.clusterset.local
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
        volumeMounts:
          - mountPath: /data
            name: data
      volumes:
        - name: data
          emptyDir: {}
