apiVersion: v1
kind: Service
metadata:
  name: redis-leader
  namespace: submariner-demo
  labels:
    app: redis-leader
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis-leader
